JosefineForsman/movie-app

- src/views/Categories/Categories.jsx
Displaying one carousel for each genre from movie data.
Filtered genre props are sent to DisplayCarousel that will later display SingleMovie in correct genre.
> data and genre function done in Categories

- src/components/DisplayCarousel/DisplayCarousel.jsx
- src/components/SingleMovie/SingleMovie.jsx
- src/views/Categories/Categories.jsx
displaycarousel takes props from categories.
SingleMovie takes props from displaycarousel.
Can see title and thumbnail in carousel that is imported to categories.
Need to handle error from image that is not working
> props in displayCarousel and singleMovie

- package-lock.json
- package.json
- src/components/SearchBar/SearchBar.test.jsx
I also installed userEvent which created changes in the package json files
> first tests created in searchbar component

- src/components/DisplayCarousel/DisplayCarousel.jsx
- src/components/SingleMovie/SingleMovie.jsx
- src/views/FilmView/FilmView.jsx
Also added the data from the clicked movie to MovieView html except actors.
Need to make a function for actors
> added all props to singleMovie

- package-lock.json
- package.json
- src/components/SingleMovie/SingleMovie.jsx
- src/components/SingleMovie/SingleMovie.scss
- src/views/Bookmarks/Bookmarks.jsx
- src/views/Bookmarks/Bookmarks.scss
Added installed package from font awesome to show the bookmarks icon.
> added bookmarks funktionality to singleMovie and filmView

- src/components/SingleMovie/SingleMovie.jsx
- src/views/Landing/Landing.test.jsx
added a test to make sure that all information is in the landing view.
> 54 test compontents in landing with unit tests

- src/components/DisplayCarousel/DisplayCarousel.jsx
- src/components/DisplayCarousel/DisplayCarousel.scss
- src/components/Footer/Footer.scss
- src/components/Header/Header.jsx
- src/components/Header/Header.scss
- src/components/Navbar/Navbar.jsx
- src/components/Navbar/Navbar.scss
- src/components/SearchBar/SearchBar.scss
- src/components/SingleMovie/SingleMovie.scss
- src/views/Categories/Categories.scss
- src/views/Landing/Landing.scss
Still got some media queries left. But added to navbar, searchbar and displayCarousel.
> media queries to header, displayCarousel + navbar

- src/views/Bookmarks/Bookmarks.scss
changed font, background colour, border radius, padding/margin, etc.
> styling on bookmarked movies

- index.html
- src/components/SingleMovie/SingleMovie.jsx
Function now compares the title of the chosen movie to the movies that are already bookmarked. (Needs more testing! Do not delete branch yet!)
> added functionality to handleFavoriteMovie

- .eslintrc.cjs
- .github/workflows/deploy.yaml
- src/components/SearchBar/SearchBar.jsx
- src/views/Bookmarks/Bookmarks.jsx
- src/views/Landing/Landing.jsx
Removed lint and test in deploy
> updated deploy.yaml

- src/components/DisplayCarousel/DisplayCarousel.jsx
- src/components/Navbar/Navbar.jsx
also deleted abundant console log
> added navigate to landing from the icon

- src/components/Footer/Footer.scss
- src/components/Navbar/Navbar.scss
- src/components/SearchBar/SearchBar.scss
- src/views/Categories/Categories.scss
- src/views/FilmView/FilmView.jsx
- src/views/FilmView/FilmView.scss
- src/views/Landing/Landing.scss
made the page responsive for a smaller screen. (280px width)
> 108 media queries for galaxy fold

- src/components/SingleMovie/SingleMovie.jsx
- src/components/SingleMovie/SingleMovie.test.jsx
Testing to render the singlemovie component with given props
> Added a test to singleMovie

- src/views/Bookmarks/Bookmarks.scss
All screen sizes are now having a good responsive layout in the grid in bookmarked movies.
> responsive grid in bookmark

- src/components/SingleMovie/SingleMovie.jsx
- src/components/SingleMovie/SingleMovie.scss
- src/components/SingleMovie/SingleMovie.test.jsx
also added css to singlemovie component with the added year
> added year to singlemovie + updated test

- src/App.test.jsx
- src/components/SingleMovie/SingleMovie.test.jsx
- src/views/Landing/Landing.test.jsx
> 129 resolving usecontext lint issues

- src/views/Bookmarks/Bookmarks.jsx
- src/views/Bookmarks/Bookmarks.scss
added text when bookmark is empty , for the user to know and for the accesability to test the bookmarks-page
> added text when bookmark is empty

- src/App.test.jsx
- src/components/LocalStorageContext/LocalStorageContext.jsx
- src/components/SingleMovie/SingleMovie.jsx
- src/views/FilmView/FilmView.jsx
- src/views/Landing/Landing.jsx
Also: MockFavoriteMoviesProvider not needed for testing. Changed in "bookmark filmview movie" test.
> Bookmark marker now stays filled

- src/components/SingleMovie/SingleMovie.jsx
- src/views/Bookmarks/Bookmarks.jsx
All problems should now be solved, with filmview, add and delete functions and bookmark icon!
> maping out singleMovie and fixed bookmark bugs.

- src/App.css
- src/components/Navbar/Navbar.scss
- src/components/SearchBar/SearchBar.jsx
- src/components/SearchBar/SearchBar.scss
- src/components/SingleMovie/SingleMovie.jsx
- src/components/SingleMovie/SingleMovie.scss
- src/views/Bookmarks/Bookmarks.jsx
- src/views/Bookmarks/Bookmarks.scss
- src/views/Categories/Categories.jsx
- src/views/Categories/Categories.scss
- src/views/FilmView/FilmView.scss
- src/views/Landing/Landing.jsx
- src/views/Landing/Landing.scss
Removed comments and empty rows where it wasnt neccesary
> clean up from various files
